# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
# By my own convention, any config object that is called *_dir must have a
# value that ends with "/"

samples: samples.tsv
output_dir: "Output/"

genome_fasta: "/project2/gilad/bjf79/genomes/GRCh38_Ensembl/Sequence/Homo_sapiens.GRCh38.dna_sm.chromosome.all.PlusHg19CircRNATargets.fa"
genome_gtf: "/project2/gilad/bjf79/genomes/GRCh38_Ensembl/Annotations/Homo_sapiens.GRCh38.94.chr.gtf"
genome_dir: "/project2/gilad/bjf79/genomes/GRCh38_Ensembl/STAR_genomedir_withCircles/"
